services:
  everydaily.api:
    image: everydaily.api
    build:
      context: .
      dockerfile: EveryDaily.Api/Dockerfile
    ports:
        - "5000:8080"
    environment: 
        - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - everydaily
    hostname: everydaily.api
    restart: always
    
networks:
  everydaily:
    external: true
